// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pulse.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulseService_Publish_FullMethodName = "/pulse.v1.PulseService/Publish"
	PulseService_Consume_FullMethodName = "/pulse.v1.PulseService/Consume"
)

// PulseServiceClient is the client API for PulseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulseServiceClient interface {
	// Publish sends a message to a topic.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Consume reads messages from a topic as a stream.
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumeResponse], error)
}

type pulseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseServiceClient(cc grpc.ClientConnInterface) PulseServiceClient {
	return &pulseServiceClient{cc}
}

func (c *pulseServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, PulseService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pulseServiceClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PulseService_ServiceDesc.Streams[0], PulseService_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, ConsumeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseService_ConsumeClient = grpc.ServerStreamingClient[ConsumeResponse]

// PulseServiceServer is the server API for PulseService service.
// All implementations must embed UnimplementedPulseServiceServer
// for forward compatibility.
type PulseServiceServer interface {
	// Publish sends a message to a topic.
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Consume reads messages from a topic as a stream.
	Consume(*ConsumeRequest, grpc.ServerStreamingServer[ConsumeResponse]) error
	mustEmbedUnimplementedPulseServiceServer()
}

// UnimplementedPulseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulseServiceServer struct{}

func (UnimplementedPulseServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPulseServiceServer) Consume(*ConsumeRequest, grpc.ServerStreamingServer[ConsumeResponse]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedPulseServiceServer) mustEmbedUnimplementedPulseServiceServer() {}
func (UnimplementedPulseServiceServer) testEmbeddedByValue()                      {}

// UnsafePulseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseServiceServer will
// result in compilation errors.
type UnsafePulseServiceServer interface {
	mustEmbedUnimplementedPulseServiceServer()
}

func RegisterPulseServiceServer(s grpc.ServiceRegistrar, srv PulseServiceServer) {
	// If the following call panics, it indicates UnimplementedPulseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulseService_ServiceDesc, srv)
}

func _PulseService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulseServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulseService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulseServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PulseService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PulseServiceServer).Consume(m, &grpc.GenericServerStream[ConsumeRequest, ConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseService_ConsumeServer = grpc.ServerStreamingServer[ConsumeResponse]

// PulseService_ServiceDesc is the grpc.ServiceDesc for PulseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulse.v1.PulseService",
	HandlerType: (*PulseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PulseService_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _PulseService_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pulse.proto",
}
